"""add_retry_count_to_scan_jobs

Revision ID: 44d4d95703c6
Revises: f3404a51c4a8
Create Date: 2026-07-20 04:53:04.725781
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44d4d95703c6'
down_revision: str | None = 'f3404a51c4a8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_jobs', sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_jobs', 'retry_count')
    # ### end Alembic commands ###
