"""m4_scheduler

Revision ID: f3404a51c4a8
Revises: 0004_m3_bot
Create Date: 2026-07-19 18:28:29.048247
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f3404a51c4a8'
down_revision: str | None = '0004_m3_bot'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_settings_key'), 'app_settings', ['key'], unique=True)
    op.create_table('quota_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('api_name', sa.String(length=32), nullable=False),
    sa.Column('units_consumed', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quota_ledger_api_name'), 'quota_ledger', ['api_name'], unique=False)
    op.create_index(op.f('ix_quota_ledger_date'), 'quota_ledger', ['date'], unique=False)
    op.create_table('scan_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'platform', name='uq_scan_job_track_platform')
    )
    op.create_index(op.f('ix_scan_jobs_platform'), 'scan_jobs', ['platform'], unique=False)
    op.create_index(op.f('ix_scan_jobs_priority'), 'scan_jobs', ['priority'], unique=False)
    op.create_index(op.f('ix_scan_jobs_status'), 'scan_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_scan_jobs_track_id'), 'scan_jobs', ['track_id'], unique=False)
    op.drop_constraint(op.f('uq_invites_token'), 'invites', type_='unique')
    op.drop_index(op.f('ix_invites_token'), table_name='invites')
    op.create_index(op.f('ix_invites_token'), 'invites', ['token'], unique=True)
    op.drop_constraint(op.f('uq_system_info_key'), 'system_info', type_='unique')
    op.drop_index(op.f('ix_system_info_key'), table_name='system_info')
    op.create_index(op.f('ix_system_info_key'), 'system_info', ['key'], unique=True)
    op.drop_constraint(op.f('uq_users_tg_user_id'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_tg_user_id'), table_name='users')
    op.create_index(op.f('ix_users_tg_user_id'), 'users', ['tg_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tg_user_id'), table_name='users')
    op.create_index(op.f('ix_users_tg_user_id'), 'users', ['tg_user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_users_tg_user_id'), 'users', ['tg_user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_system_info_key'), table_name='system_info')
    op.create_index(op.f('ix_system_info_key'), 'system_info', ['key'], unique=False)
    op.create_unique_constraint(op.f('uq_system_info_key'), 'system_info', ['key'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_invites_token'), table_name='invites')
    op.create_index(op.f('ix_invites_token'), 'invites', ['token'], unique=False)
    op.create_unique_constraint(op.f('uq_invites_token'), 'invites', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_scan_jobs_track_id'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_status'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_priority'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_platform'), table_name='scan_jobs')
    op.drop_table('scan_jobs')
    op.drop_index(op.f('ix_quota_ledger_date'), table_name='quota_ledger')
    op.drop_index(op.f('ix_quota_ledger_api_name'), table_name='quota_ledger')
    op.drop_table('quota_ledger')
    op.drop_index(op.f('ix_app_settings_key'), table_name='app_settings')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
