"""ORM models.

Importing everything here means `app.models.Base.metadata` is complete, which is
what Alembic's autogenerate and the metadata target rely on.
"""

from app.models.artist import ROLE_EDITOR, ROLE_OWNER, ROLE_VIEWER, Artist, ArtistMember
from app.models.audit import AuditEvent
from app.models.base import Base
from app.models.detection import (
    BAND_HIGH,
    BAND_LOW,
    BAND_MID,
    PE_APPLE_LABEL,
    PE_DISTRIBUTOR,
    PE_SPOTIFY_LABEL,
    PE_YT_CHANNEL,
    PLATFORM_ITUNES,
    PLATFORM_SPOTIFY,
    PLATFORM_YOUTUBE,
    RESOLVED_STATUSES,
    STATUS_CONFIRMED,
    STATUS_DETECTED,
    STATUS_DISMISSED,
    STATUS_PENDING_REVIEW,
    STATUS_REMIX_REVIEW,
    STATUS_TOLERATED,
    WL_APPLE_ARTIST,
    WL_CHANNEL,
    WL_ISRC,
    WL_OWN_LABEL,
    WL_PLATFORM_ID,
    WL_SCOPE_ARTIST,
    WL_SCOPE_GLOBAL,
    WL_SCOPE_TRACK,
    WL_SPOTIFY_ARTIST,
    Finding,
    FindingEvent,
    PirateEntity,
    PlatformCandidate,
    WhitelistEntry,
)
from app.models.notify import (
    KIND_ADMIN_ALERT,
    KIND_DIGEST,
    KIND_FINDING,
    MAX_OUTBOX_ATTEMPTS,
    MODE_DAILY,
    MODE_INSTANT,
    MODE_WEEKLY,
    OUTBOX_FAILED,
    OUTBOX_PENDING,
    OUTBOX_SENT,
    NotificationOutbox,
    Subscription,
)
from app.models.system import SystemInfo
from app.models.track import (
    AUDIO_REF_FULL,
    AUDIO_REF_NONE,
    AUDIO_REF_PREVIEW,
    Track,
    TrackArtist,
)
from app.models.user import Invite, User

__all__ = [
    "Base",
    "SystemInfo",
    "User",
    "Invite",
    "Artist",
    "ArtistMember",
    "Track",
    "TrackArtist",
    "AuditEvent",
    "ROLE_OWNER",
    "ROLE_EDITOR",
    "ROLE_VIEWER",
    "AUDIO_REF_NONE",
    "AUDIO_REF_PREVIEW",
    "AUDIO_REF_FULL",
    # Detection (M2)
    "PlatformCandidate",
    "Finding",
    "FindingEvent",
    "WhitelistEntry",
    "PirateEntity",
    "PLATFORM_SPOTIFY",
    "PLATFORM_ITUNES",
    "PLATFORM_YOUTUBE",
    "BAND_HIGH",
    "BAND_MID",
    "BAND_LOW",
    "STATUS_DETECTED",
    "STATUS_PENDING_REVIEW",
    "STATUS_REMIX_REVIEW",
    "STATUS_CONFIRMED",
    "STATUS_DISMISSED",
    "STATUS_TOLERATED",
    "RESOLVED_STATUSES",
    "WL_OWN_LABEL",
    "WL_ISRC",
    "WL_SPOTIFY_ARTIST",
    "WL_APPLE_ARTIST",
    "WL_CHANNEL",
    "WL_PLATFORM_ID",
    "WL_SCOPE_GLOBAL",
    "WL_SCOPE_ARTIST",
    "WL_SCOPE_TRACK",
    "PE_YT_CHANNEL",
    "PE_SPOTIFY_LABEL",
    "PE_APPLE_LABEL",
    "PE_DISTRIBUTOR",
    # Notifications (M3)
    "Subscription",
    "NotificationOutbox",
    "MODE_INSTANT",
    "MODE_DAILY",
    "MODE_WEEKLY",
    "OUTBOX_PENDING",
    "OUTBOX_SENT",
    "OUTBOX_FAILED",
    "KIND_FINDING",
    "KIND_DIGEST",
    "KIND_ADMIN_ALERT",
    "MAX_OUTBOX_ATTEMPTS",
]
